In [1]:
inputs = '''C	AC	AC
都好	都好	都好
BC	BC	BC
都好	都好	都好
都好	C	AC
都不好	C	C
C	C	C
C	BC	BC
C	都不好	C
B	BC	BC
C	C	C
都不好	C	C
C	B	C
BC	B	B
C	B	C
C	都不好	C
都好	AB	AB
C	A	C
C	C	C
都不好	B	C
BC	C	B
C	C	C
C	都不好	C
都不好	C	C
都不好	B	B
C	BC	BC
BC	B	BC
都不好	都不好	B
BC	都好	BC
BC	BC	B
BC	BC	BC
C	BC	C
都不好	都不好	C
C	C	C
都不好	B	B
都不好	都不好	B
C	C	C
C	C	A
都不好	都不好	B
C	都不好	A
C	都不好	AC
B	都不好	B
C	都不好	C
C	都不好	A
都好	A	A
C	C	C
C	C	C
C	C	C
C	C	C
C	B	C
C	C	C
都好	B	BC
C	A	A
AC	A	A
AC	都不好	A
BC	C	C
BC	C	B
BC	B	B
BC	C	BC
BC	C	BC
B	B	C
BC	C	B
都好	C	C
都好	都好	B
都好	BC	B
BC	BC	B
AC	C	A
BC	BC	C
AC	AC	A
C	C	C
都好	都好	C
A	A	A
A	AC	A
C	C	C
C	C	C
AC	C	C
都好	A	A
AC	C	A
AC	C	C
AC	AC	C
C	B	C
都好	BC	A
都好	A	都不好
AB	A	A
C	C	C
AC	C	A
AC	都不好	C
AB	都不好	C
AC	AC	C
C	AC	A
A	AC	A
都好	B	A
C	C	C
B	都不好	B
C	都不好	A
C	C	C
C	都不好	都不好
B	B	C
BC	BC	C
C	C	C
C	C	都不好
C	BC	都不好
都不好	A	都不好
B	都不好	都不好
B	BC	B
BC	BC	B
B	BC	C
都不好	都不好	都不好
都不好	都不好	都不好
C	C	C
C	C	C
C	C	都不好
C	BC	都不好
C	C	都不好
B	B	B
AB	BC	B
BC	BC	C
C	C	C
BC	BC	C
C	C	C
A	都好	B
都好	AB	B
C	C	C
C	C	C
BC	C	都不好
C	C	C
都不好	都不好	都不好
C	C	都不好
C	C	都不好
C	C	都不好
C	C	C'''

In [2]:
import numpy as np
a_score_list, b_score_list, c_score_list = [], [], []

def check_tag(input):
    if input == 'A':
        return [3, 0, 0]
    elif input == 'B':
        return [0, 3, 0]
    elif input == 'C':
        return [0, 0, 3]
    elif input == 'AC':
        return [1.5, 0, 1.5]
    elif input == 'BC':
        return [0, 1.5, 1.5]
    elif input == 'AB':
        return [1.5, 1.5, 0]
    elif  input == '都好':
        return [1, 1, 1]
    elif input == '都不好':
        return [0, 0, 0]
    else:
        print('input error')

def check(tmp_a, tmp_b, tmp_c):
    a_tmp = check_tag(tmp_a)
    b_tmp = check_tag(tmp_b)
    c_tmp = check_tag(tmp_c)
    
    all_tmp = np.sum([a_tmp, b_tmp, c_tmp], axis=0)
    print(all_tmp)

    return all_tmp

inputs = inputs.split('\n')

for line in inputs:
    print(line)
    cut = line.split('\t')
    tmp_a, tmp_b, tmp_c = cut[0], cut[1], cut[2]
    all_score = check(tmp_a, tmp_b, tmp_c)
    a_score_list.append(all_score[0])
    b_score_list.append(all_score[1])
    c_score_list.append(all_score[2])

print(a_score_list)
print(b_score_list)
print(c_score_list)

C	AC	AC
[3. 0. 6.]
都好	都好	都好
[3 3 3]
BC	BC	BC
[0.  4.5 4.5]
都好	都好	都好
[3 3 3]
都好	C	AC
[2.5 1.  5.5]
都不好	C	C
[0 0 6]
C	C	C
[0 0 9]
C	BC	BC
[0. 3. 6.]
C	都不好	C
[0 0 6]
B	BC	BC
[0. 6. 3.]
C	C	C
[0 0 9]
都不好	C	C
[0 0 6]
C	B	C
[0 3 6]
BC	B	B
[0.  7.5 1.5]
C	B	C
[0 3 6]
C	都不好	C
[0 0 6]
都好	AB	AB
[4. 4. 1.]
C	A	C
[3 0 6]
C	C	C
[0 0 9]
都不好	B	C
[0 3 3]
BC	C	B
[0.  4.5 4.5]
C	C	C
[0 0 9]
C	都不好	C
[0 0 6]
都不好	C	C
[0 0 6]
都不好	B	B
[0 6 0]
C	BC	BC
[0. 3. 6.]
BC	B	BC
[0. 6. 3.]
都不好	都不好	B
[0 3 0]
BC	都好	BC
[1. 4. 4.]
BC	BC	B
[0. 6. 3.]
BC	BC	BC
[0.  4.5 4.5]
C	BC	C
[0.  1.5 7.5]
都不好	都不好	C
[0 0 3]
C	C	C
[0 0 9]
都不好	B	B
[0 6 0]
都不好	都不好	B
[0 3 0]
C	C	C
[0 0 9]
C	C	A
[3 0 6]
都不好	都不好	B
[0 3 0]
C	都不好	A
[3 0 3]
C	都不好	AC
[1.5 0.  4.5]
B	都不好	B
[0 6 0]
C	都不好	C
[0 0 6]
C	都不好	A
[3 0 3]
都好	A	A
[7 1 1]
C	C	C
[0 0 9]
C	C	C
[0 0 9]
C	C	C
[0 0 9]
C	C	C
[0 0 9]
C	B	C
[0 3 6]
C	C	C
[0 0 9]
都好	B	BC
[1.  5.5 2.5]
C	A	A
[6 0 3]
AC	A	A
[7.5 0.  1.5]
AC	都不好	A
[4.5 0.  1.5]
BC	C	C
[0.  1.5 7.5]
BC	C	B
[0.  4.5 4.5]
BC	B	B
[0.  7.5 1

In [3]:
print(sum(a_score_list))
print(sum(b_score_list))
print(sum(c_score_list))

162.5
245.0
615.5


In [4]:
inputs = '''C	AC	AC
都好	都好	都好
BC	BC	BC
都好	都好	都好
都好	C	AC
都不好	C	C
C	C	C
C	BC	BC
C	都不好	C
B	BC	BC
C	C	C
都不好	C	C
C	B	C
BC	B	B
C	B	C
C	都不好	C
都好	AB	AB
C	A	C
C	C	C
都不好	B	C
BC	C	B
C	C	C
C	都不好	C
都不好	C	C
都不好	B	B
C	BC	BC
BC	B	BC
都不好	都不好	B
BC	都好	BC
BC	BC	B
BC	BC	BC
C	BC	C
都不好	都不好	C
C	C	C
都不好	B	B
都不好	都不好	B
C	C	C
C	C	A
都不好	都不好	B
C	都不好	A
C	都不好	AC
B	都不好	B
C	都不好	C
C	都不好	A
都好	A	A
C	C	C
C	C	C
C	C	C
C	C	C
C	B	C
C	C	C
都好	B	BC
C	A	A
AC	A	A
AC	都不好	A
BC	C	C
BC	C	B
BC	B	B
BC	C	BC
BC	C	BC
B	B	C
BC	C	B
都好	C	C
都好	都好	B
都好	BC	B
C	C	C
AC	C	A
AC	都不好	C
AB	都不好	C
AC	AC	C
C	AC	A
A	AC	A
都好	B	A
C	C	C
B	都不好	B
C	都不好	A
C	C	C
C	都不好	都不好
B	B	C
BC	BC	C
C	C	C
C	C	都不好
C	BC	都不好
都不好	A	都不好
B	都不好	都不好
B	BC	B
BC	BC	B
B	BC	C
都不好	都不好	都不好
都不好	都不好	都不好
C	C	C
C	C	C
C	C	都不好
C	BC	都不好
C	C	都不好
B	B	B
AB	BC	B
BC	BC	C
C	C	C
BC	BC	C
C	C	C
A	都好	B
都好	AB	B
C	C	C
C	C	C
BC	C	都不好
C	C	C
都不好	都不好	都不好
C	C	都不好
C	C	都不好
C	C	都不好
C	C	C'''

In [5]:
import numpy as np
a_score_list, b_score_list, c_score_list = [], [], []

def check_tag(input):
    if input == 'A':
        return [3, 0, 0]
    elif input == 'B':
        return [0, 3, 0]
    elif input == 'C':
        return [0, 0, 3]
    elif input == 'AC':
        return [1.5, 0, 1.5]
    elif input == 'BC':
        return [0, 1.5, 1.5]
    elif input == 'AB':
        return [1.5, 1.5, 0]
    elif  input == '都好':
        return [1, 1, 1]
    elif input == '都不好':
        return [0, 0, 0]
    else:
        print('input error')

def check(tmp_a, tmp_b, tmp_c):
    a_tmp = check_tag(tmp_a)
    b_tmp = check_tag(tmp_b)
    c_tmp = check_tag(tmp_c)
    
    all_tmp = np.sum([a_tmp, b_tmp, c_tmp], axis=0)
    print(all_tmp)

    return all_tmp

inputs = inputs.split('\n')

for line in inputs:
    print(line)
    cut = line.split('\t')
    tmp_a, tmp_b, tmp_c = cut[0], cut[1], cut[2]
    all_score = check(tmp_a, tmp_b, tmp_c)
    a_score_list.append(all_score[0])
    b_score_list.append(all_score[1])
    c_score_list.append(all_score[2])

print(a_score_list)
print(b_score_list)
print(c_score_list)

C	AC	AC
[3. 0. 6.]
都好	都好	都好
[3 3 3]
BC	BC	BC
[0.  4.5 4.5]
都好	都好	都好
[3 3 3]
都好	C	AC
[2.5 1.  5.5]
都不好	C	C
[0 0 6]
C	C	C
[0 0 9]
C	BC	BC
[0. 3. 6.]
C	都不好	C
[0 0 6]
B	BC	BC
[0. 6. 3.]
C	C	C
[0 0 9]
都不好	C	C
[0 0 6]
C	B	C
[0 3 6]
BC	B	B
[0.  7.5 1.5]
C	B	C
[0 3 6]
C	都不好	C
[0 0 6]
都好	AB	AB
[4. 4. 1.]
C	A	C
[3 0 6]
C	C	C
[0 0 9]
都不好	B	C
[0 3 3]
BC	C	B
[0.  4.5 4.5]
C	C	C
[0 0 9]
C	都不好	C
[0 0 6]
都不好	C	C
[0 0 6]
都不好	B	B
[0 6 0]
C	BC	BC
[0. 3. 6.]
BC	B	BC
[0. 6. 3.]
都不好	都不好	B
[0 3 0]
BC	都好	BC
[1. 4. 4.]
BC	BC	B
[0. 6. 3.]
BC	BC	BC
[0.  4.5 4.5]
C	BC	C
[0.  1.5 7.5]
都不好	都不好	C
[0 0 3]
C	C	C
[0 0 9]
都不好	B	B
[0 6 0]
都不好	都不好	B
[0 3 0]
C	C	C
[0 0 9]
C	C	A
[3 0 6]
都不好	都不好	B
[0 3 0]
C	都不好	A
[3 0 3]
C	都不好	AC
[1.5 0.  4.5]
B	都不好	B
[0 6 0]
C	都不好	C
[0 0 6]
C	都不好	A
[3 0 3]
都好	A	A
[7 1 1]
C	C	C
[0 0 9]
C	C	C
[0 0 9]
C	C	C
[0 0 9]
C	C	C
[0 0 9]
C	B	C
[0 3 6]
C	C	C
[0 0 9]
都好	B	BC
[1.  5.5 2.5]
C	A	A
[6 0 3]
AC	A	A
[7.5 0.  1.5]
AC	都不好	A
[4.5 0.  1.5]
BC	C	C
[0.  1.5 7.5]
BC	C	B
[0.  4.5 4.5]
BC	B	B
[0.  7.5 1

In [0]:
print(sum(a_score_list))
print(sum(b_score_list))
print(sum(c_score_list))