In [3]:
import numpy as np 

context = '汉堡好吃'
query = '吃啥呢'

context_index = [[0.2]*3, [0.3]*3, [0.4]*3, [0.5]*3]
query_index = [[0.6]*3, [0.7]*3, [0.8]*3]

context_index = np.asarray(context_index)
query_index = np.asarray(query_index)

print(context_index)
print(query_index)

[[0.2 0.2 0.2]
 [0.3 0.3 0.3]
 [0.4 0.4 0.4]
 [0.5 0.5 0.5]]
[[0.6 0.6 0.6]
 [0.7 0.7 0.7]
 [0.8 0.8 0.8]]


In [6]:
s = np.matmul(context_index, query_index.T)
print(s)

[[0.36 0.42 0.48]
 [0.54 0.63 0.72]
 [0.72 0.84 0.96]
 [0.9  1.05 1.2 ]]
